#!/usr/bin/env python

# Copyright 2024 Columbia Artificial Intelligence, Robotics Lab,
# and The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Diffusion Policy as per "Diffusion Policy: Visuomotor Policy Learning via Action Diffusion"

TODO(alexander-soare):
  - Remove reliance on diffusers for DDPMScheduler and LR scheduler.
"""

import json
import math
from collections import deque

import einops
import torch
import torch.nn.functional as F  # noqa: N812
from diffusers.schedulers.scheduling_ddim import DDIMScheduler
from diffusers.schedulers.scheduling_ddpm import DDPMScheduler
from torch import Tensor, nn

from lerobot.policies.ours_diffusion.configuration_diffusion import OursDiffusionConfig
from lerobot.policies.ours_diffusion.ours_encoder import OursDiffusionRgbEncoder
from lerobot.policies.pretrained import PreTrainedPolicy
from lerobot.policies.utils import (
    get_device_from_parameters,
    get_dtype_from_parameters,
    populate_queues,
)
from lerobot.utils.constants import ACTION, OBS_ENV_STATE, OBS_IMAGES, OBS_STATE

METAWORLD_CAM_WORLD_POS = (0.75, 0.075, 0.7)
METAWORLD_CAM_WORLD_ROT = (
    (-0.54990133, 0.37620774, 0.74570521),
    (-0.83318276, -0.30954914, -0.45824210),
    (0.05843818, -0.87329666, 0.48367129),
)
METAWORLD_CAM_FOVY = 60.0
METAWORLD_MOCAP_LOW = (-0.2, 0.5, 0.06)
METAWORLD_MOCAP_HIGH = (0.2, 0.7, 0.6)
IMAGE_HEIGHT = 224
IMAGE_WIDTH = 224


class OursDiffusionPolicy(PreTrainedPolicy):
    """
    Diffusion Policy as per "Diffusion Policy: Visuomotor Policy Learning via Action Diffusion"
    (paper: https://huggingface.co/papers/2303.04137, code: https://github.com/real-stanford/diffusion_policy).
    """

    config_class = OursDiffusionConfig
    name = "ours_diffusion"

    def __init__(
        self,
        config: OursDiffusionConfig,
    ):
        """
        Args:
            config: Policy configuration class instance or None, in which case the default instantiation of
                the configuration class is used.
            dataset_stats: Dataset statistics to be used for normalization. If not passed here, it is expected
                that they will be passed with a call to `load_state_dict` before the policy is used.
        """
        super().__init__(config)
        config.validate_features()
        self.config = config

        # queues are populated during rollout of the policy, they contain the n latest observations and actions
        self._queues = None

        self.diffusion = DiffusionModel(config)

        self.reset()

    def get_optim_params(self) -> dict:
        return self.diffusion.parameters()

    def reset(self):
        """Clear observation and action queues. Should be called on `env.reset()`"""
        self._queues = {
            OBS_STATE: deque(maxlen=self.config.n_obs_steps),
            ACTION: deque(maxlen=self.config.n_action_steps),
        }
        if self.config.image_features:
            self._queues[OBS_IMAGES] = deque(maxlen=self.config.n_obs_steps)
        if self.config.env_state_feature:
            self._queues[OBS_ENV_STATE] = deque(maxlen=self.config.n_obs_steps)

    @torch.no_grad()
    def predict_action_chunk(
        self, batch: dict[str, Tensor], raw_states: Tensor, noise: Tensor | None = None
    ) -> Tensor:
        """Predict a chunk of actions given environment observations."""
        # stack n latest observations from the queue
        batch = {k: torch.stack(list(self._queues[k]), dim=1) for k in batch if k in self._queues}
        actions = self.diffusion.generate_actions(batch, raw_states, noise=noise)

        return actions

    @torch.no_grad()
    def select_action(
        self, batch: dict[str, Tensor], raw_states: Tensor, noise: Tensor | None = None
    ) -> Tensor:
        """Select a single action given environment observations.

        This method handles caching a history of observations and an action trajectory generated by the
        underlying diffusion model. Here's how it works:
          - `n_obs_steps` steps worth of observations are cached (for the first steps, the observation is
            copied `n_obs_steps` times to fill the cache).
          - The diffusion model generates `horizon` steps worth of actions.
          - `n_action_steps` worth of actions are actually kept for execution, starting from the current step.
        Schematically this looks like:
            ----------------------------------------------------------------------------------------------
            (legend: o = n_obs_steps, h = horizon, a = n_action_steps)
            |timestep            | n-o+1 | n-o+2 | ..... | n     | ..... | n+a-1 | n+a   | ..... | n-o+h |
            |observation is used | YES   | YES   | YES   | YES   | NO    | NO    | NO    | NO    | NO    |
            |action is generated | YES   | YES   | YES   | YES   | YES   | YES   | YES   | YES   | YES   |
            |action is used      | NO    | NO    | NO    | YES   | YES   | YES   | NO    | NO    | NO    |
            ----------------------------------------------------------------------------------------------
        Note that this means we require: `n_action_steps <= horizon - n_obs_steps + 1`. Also, note that
        "horizon" may not the best name to describe what the variable actually means, because this period is
        actually measured from the first observation which (if `n_obs_steps` > 1) happened in the past.
        """
        # NOTE: for offline evaluation, we have action in the batch, so we need to pop it out
        assert raw_states.shape[-1] == 3  # 3d position

        if ACTION in batch:
            batch.pop(ACTION)

        if self.config.image_features:
            batch = dict(batch)  # shallow copy so that adding a key doesn't modify the original
            batch[OBS_IMAGES] = torch.stack([batch[key] for key in self.config.image_features], dim=-4)
        # NOTE: It's important that this happens after stacking the images into a single key.
        self._queues = populate_queues(self._queues, batch)

        if len(self._queues[ACTION]) == 0:
            actions = self.predict_action_chunk(batch, raw_states, noise=noise)
            self._queues[ACTION].extend(actions.transpose(0, 1))

        action = self._queues[ACTION].popleft()
        return action

    def forward(self, batch: dict[str, Tensor], raw_states: Tensor) -> tuple[Tensor, None]:
        """Run the batch through the model and compute the loss for training or validation."""
        if self.config.image_features:
            batch = dict(batch)  # shallow copy so that adding a key doesn't modify the original
            batch[OBS_IMAGES] = torch.stack([batch[key] for key in self.config.image_features], dim=-4)
        loss = self.diffusion.compute_loss(batch, raw_states)
        # no output_dict so returning None
        return loss, None


def _make_noise_scheduler(name: str, **kwargs: dict) -> DDPMScheduler | DDIMScheduler:
    """
    Factory for noise scheduler instances of the requested type. All kwargs are passed
    to the scheduler.
    """
    if name == "DDPM":
        return DDPMScheduler(**kwargs)
    elif name == "DDIM":
        return DDIMScheduler(**kwargs)
    else:
        raise ValueError(f"Unsupported noise scheduler type {name}")


class DiffusionModel(nn.Module):
    def __init__(self, config: OursDiffusionConfig):
        super().__init__()
        self.config = config

        # Build observation encoders (depending on which observations are provided).
        global_cond_dim = self.config.robot_state_feature.shape[0]
        if self.config.image_features:
            num_images = len(self.config.image_features)
            if self.config.use_separate_rgb_encoder_per_camera:
                encoders = [OursDiffusionRgbEncoder(config) for _ in range(num_images)]
                self.rgb_encoder = nn.ModuleList(encoders)
                global_cond_dim += encoders[0].feature_dim * num_images
            else:
                self.rgb_encoder = OursDiffusionRgbEncoder(config)
                global_cond_dim += self.rgb_encoder.feature_dim * num_images
        if self.config.env_state_feature:
            global_cond_dim += self.config.env_state_feature.shape[0]

        self.unet = DiffusionConditionalUnet1d(config, global_cond_dim=global_cond_dim * config.n_obs_steps)

        self.noise_scheduler = _make_noise_scheduler(
            config.noise_scheduler_type,
            num_train_timesteps=config.num_train_timesteps,
            beta_start=config.beta_start,
            beta_end=config.beta_end,
            beta_schedule=config.beta_schedule,
            clip_sample=config.clip_sample,
            clip_sample_range=config.clip_sample_range,
            prediction_type=config.prediction_type,
        )

        if config.num_inference_steps is None:
            self.num_inference_steps = self.noise_scheduler.config.num_train_timesteps
        else:
            self.num_inference_steps = config.num_inference_steps
        self._inference_schedule_key = None
        self._model_timesteps = None

        action_min = config.action_min
        action_max = config.action_max
        if action_min is None or action_max is None:
            if config.dataset_stats_path is None:
                raise ValueError(
                    "SCDP needs action bounds. Set `action_min`/`action_max`, or provide "
                    "`dataset_stats_path` for a legacy checkpoint."
                )
            with open(config.dataset_stats_path) as f:
                stats = json.load(f)
            action_min = tuple(stats["action"]["min"][:3])
            action_max = tuple(stats["action"]["max"][:3])

        self.register_buffer("action_min", torch.tensor(action_min, dtype=torch.float32), persistent=False)
        self.register_buffer("action_max", torch.tensor(action_max, dtype=torch.float32), persistent=False)
        self.register_buffer(
            "metaworld_cam_world_pos",
            torch.tensor(METAWORLD_CAM_WORLD_POS, dtype=torch.float32),
            persistent=False,
        )
        self.register_buffer(
            "metaworld_cam_world_rot",
            torch.tensor(METAWORLD_CAM_WORLD_ROT, dtype=torch.float32),
            persistent=False,
        )
        self.register_buffer(
            "metaworld_mocap_low",
            torch.tensor(METAWORLD_MOCAP_LOW, dtype=torch.float32),
            persistent=False,
        )
        self.register_buffer(
            "metaworld_mocap_high",
            torch.tensor(METAWORLD_MOCAP_HIGH, dtype=torch.float32),
            persistent=False,
        )

        fovy = math.radians(METAWORLD_CAM_FOVY)
        self.fy = (IMAGE_HEIGHT / 2) / math.tan(fovy / 2)
        self.fx = self.fy * (IMAGE_WIDTH / IMAGE_HEIGHT)
        self.cx = IMAGE_WIDTH / 2
        self.cy = IMAGE_HEIGHT / 2

    def _prepare_state_conditioning(self, batch: dict[str, Tensor]) -> Tensor:
        """
        Returns: ((b s), state_dim) global conditioning feature vector.
        """
        global_cond_feats = batch[OBS_STATE]
        global_cond_feats = einops.rearrange(global_cond_feats, "b s ... -> (b s) ...")  # ((b s), state_dim)
        return global_cond_feats

    def _prepare_image_feature_maps(self, batch: dict[str, Tensor]) -> list[Tensor]:
        """
        Returns: list of ((b s n), C, H, W) feature maps extracted from images.
        """
        img_features = self.rgb_encoder(einops.rearrange(batch[OBS_IMAGES], "b s n ... -> (b s n) ..."))
        return img_features

    def _grid_sampling(self, image_feature_maps: list[Tensor], raw_states: Tensor) -> Tensor:
        """Given a list of feature maps, extract a fixed number of features from each map
        by sampling them on a grid.

        Args:
            image_feature_maps: List of ((b s n), C, H, W) feature maps extracted from images.
            raw_states: ((b s), p, 2), normalized x,y positions in [-1, 1] range.
            num_samples_per_map: Number of features to sample from each feature map.

        Returns:
            ((b s n), c')
        """
        # https://docs.pytorch.org/docs/stable/generated/torch.nn.functional.grid_sample.html
        grid = raw_states.unsqueeze(2).float()

        # ((b s n), c, p, 1) -> ((b s n), c, p)
        sample_a = F.grid_sample(
            image_feature_maps[0], grid, mode="bilinear", padding_mode="border", align_corners=False
        ).squeeze(-1)
        sample_b = F.grid_sample(
            image_feature_maps[1], grid, mode="bilinear", padding_mode="border", align_corners=False
        ).squeeze(-1)
        sample_c = F.grid_sample(
            image_feature_maps[2], grid, mode="bilinear", padding_mode="border", align_corners=False
        ).squeeze(-1)
        sample_d = F.grid_sample(
            image_feature_maps[3], grid, mode="bilinear", padding_mode="border", align_corners=False
        ).squeeze(-1)
        sample_e = F.grid_sample(
            image_feature_maps[4], grid, mode="bilinear", padding_mode="border", align_corners=False
        ).squeeze(-1)

        sample_a = sample_a.mean(dim=-1)
        sample_b = sample_b.mean(dim=-1)
        sample_c = sample_c.mean(dim=-1)
        sample_d = sample_d.mean(dim=-1)
        sample_e = sample_e.mean(dim=-1)

        sample = torch.cat([sample_a, sample_b, sample_c, sample_d, sample_e], dim=-1)  # ((b s n), c*5)
        return sample

    def _dynamic_conditioning(
        self, image_feature_maps: list[Tensor], states: Tensor, state_cond: Tensor
    ) -> Tensor:
        states = einops.rearrange(states, "b s p ... -> (b s) p ...")  # ((b s), 2)
        image_cond = self._grid_sampling(image_feature_maps=image_feature_maps, raw_states=states)
        dynamic_cond = torch.cat([state_cond, image_cond], dim=-1)
        return dynamic_cond

    def _metaworld_projection(self, raw_states: Tensor) -> Tensor:
        hand_cam_pos = (raw_states - self.metaworld_cam_world_pos) @ self.metaworld_cam_world_rot
        hand_cam_pos_invz = hand_cam_pos[:, :, 2].reciprocal()

        u = self.fx * (hand_cam_pos[:, :, 0] * hand_cam_pos_invz) + self.cx
        v = self.fy * (hand_cam_pos[:, :, 1] * -hand_cam_pos_invz) + self.cy
        state = torch.stack([u, v], dim=-1)

        # Normalize projected pixel coordinates to the grid_sample range.
        state[:, :, 0] = 2 * (state[:, :, 0] / IMAGE_WIDTH) - 1
        state[:, :, 1] = 2 * (state[:, :, 1] / IMAGE_HEIGHT) - 1
        return state

    def _metaworld_movement(
        self,
        current_states: Tensor,
        delta_states: Tensor,
        action_scale: float = 1.0 / 100,
    ) -> Tensor:
        delta_states = torch.clamp(delta_states, min=-1, max=1) * action_scale
        next_states = current_states + delta_states
        next_states = torch.clamp(
            next_states,
            min=self.metaworld_mocap_low,
            max=self.metaworld_mocap_high,
        )

        return next_states

    def _action_unnormalizer(self, actions: Tensor) -> Tensor:
        actions = (actions + 1.0) / 2.0  # [0, 1]
        unnormalized_actions = self.action_min + actions * (self.action_max - self.action_min)
        return unnormalized_actions

    # ========= inference  ============
    @torch.no_grad()
    def conditional_sample(
        self,
        batch: Tensor,
        raw_states: Tensor | None = None,
        generator: torch.Generator | None = None,
        noise: Tensor | None = None,
    ) -> Tensor:
        device = get_device_from_parameters(self)
        dtype = get_dtype_from_parameters(self)

        batch_size, n_obs_steps = batch[OBS_STATE].shape[:2]
        assert n_obs_steps == self.config.n_obs_steps

        state_cond = self._prepare_state_conditioning(batch)  # (B, s, state_dim)
        image_feature_maps = self._prepare_image_feature_maps(batch)

        # Sample prior.
        sample = (
            noise
            if noise is not None
            else torch.randn(
                size=(batch_size, self.config.horizon, self.config.action_feature.shape[0]),
                dtype=dtype,
                device=device,
                generator=generator,
            )
        )

        # Scheduler timesteps stay on CPU for scheduler.step(), while one GPU copy is
        # cached for the U-Net. This avoids rebuilding the schedule and allocating a
        # new timestep batch at every denoising step and action chunk.
        schedule_key = (self.num_inference_steps, device)
        if self._inference_schedule_key != schedule_key:
            self.noise_scheduler.set_timesteps(self.num_inference_steps)
            self._model_timesteps = self.noise_scheduler.timesteps.to(device=device)
            self._inference_schedule_key = schedule_key

        for t, model_t in zip(self.noise_scheduler.timesteps, self._model_timesteps, strict=True):
            # Dynamic Conditioning
            dynamic_states = raw_states
            projected_raw_states = self._metaworld_projection(raw_states)
            state_list = [projected_raw_states]

            for i in range(1, 1 + self.config.sample_step):
                delta_states = self._action_unnormalizer(sample[:, i, :3]).unsqueeze(1).expand(-1, 2, -1)
                dynamic_states = self._metaworld_movement(dynamic_states, delta_states)
                projected_dynamic_states = self._metaworld_projection(dynamic_states)

                state_list.append(projected_dynamic_states)
            states = torch.stack(state_list, dim=2)  # (b, s, p, 2)

            dynamic_cond = self._dynamic_conditioning(image_feature_maps, states, state_cond)
            dynamic_cond = einops.rearrange(
                dynamic_cond, "(b s) ... -> b (s ...)", b=batch_size, s=n_obs_steps
            )  # (b, global_cond_dim)

            # Predict model output.
            model_output = self.unet(
                sample,
                model_t.expand(batch_size),
                global_cond=dynamic_cond,
            )
            # Compute previous image: x_t -> x_t-1
            sample = self.noise_scheduler.step(model_output, t, sample, generator=generator).prev_sample

        return sample

    def generate_actions(
        self, batch: dict[str, Tensor], raw_states: Tensor, noise: Tensor | None = None
    ) -> Tensor:
        """
        This function expects `batch` to have:
        {
            "observation.state": (B, n_obs_steps, state_dim)

            "observation.images": (B, n_obs_steps, num_cameras, C, H, W)
                AND/OR
            "observation.environment_state": (B, n_obs_steps, environment_dim)
        }
        """
        batch_size, n_obs_steps = batch[OBS_STATE].shape[:2]
        assert n_obs_steps == self.config.n_obs_steps

        # run sampling
        actions = self.conditional_sample(batch, raw_states=raw_states, noise=noise)

        # Extract `n_action_steps` steps worth of actions (from the current observation).
        start = n_obs_steps - 1
        end = start + self.config.n_action_steps
        actions = actions[:, start:end]

        return actions

    def compute_loss(self, batch: dict[str, Tensor], raw_states: Tensor) -> Tensor:
        """
        This function expects `batch` to have (at least):
        {
            "observation.state": (B, n_obs_steps, state_dim)

            "observation.images": (B, n_obs_steps, num_cameras, C, H, W)
                AND/OR
            "observation.environment_state": (B, n_obs_steps, environment_dim)

            "action": (B, horizon, action_dim)
            "action_is_pad": (B, horizon)
        }
        """
        # Input validation.
        assert set(batch).issuperset({OBS_STATE, ACTION, "action_is_pad"})
        assert OBS_IMAGES in batch or OBS_ENV_STATE in batch
        batch_size = batch[OBS_STATE].shape[0]
        n_obs_steps = batch[OBS_STATE].shape[1]
        horizon = batch[ACTION].shape[1]
        assert horizon == self.config.horizon
        assert n_obs_steps == self.config.n_obs_steps
        assert raw_states.shape[-1] == 3  # 3d position

        # Encode image features and concatenate them all together along with the state vector.
        state_cond = self._prepare_state_conditioning(batch)  # (b s), state_dim)

        image_feature_maps = self._prepare_image_feature_maps(batch)

        # Forward diffusion.
        trajectory = batch[ACTION]
        # Sample noise to add to the trajectory.
        eps = torch.randn(trajectory.shape, device=trajectory.device)
        # Sample a random noising timestep for each item in the batch.
        timesteps = torch.randint(
            low=0,
            high=self.noise_scheduler.config.num_train_timesteps,
            size=(trajectory.shape[0],),
            device=trajectory.device,
        ).long()
        # Add noise to the clean trajectories according to the noise magnitude at each timestep.
        noisy_trajectory = self.noise_scheduler.add_noise(trajectory, eps, timesteps)

        # Dynamic Conditioning
        with torch.no_grad():
            dynamic_states = raw_states
            projected_raw_states = self._metaworld_projection(raw_states)
            state_list = [projected_raw_states]

            for i in range(1, 1 + self.config.sample_step):
                delta_states = (
                    self._action_unnormalizer(noisy_trajectory[:, i, :3]).unsqueeze(1).expand(-1, 2, -1)
                )
                dynamic_states = self._metaworld_movement(dynamic_states, delta_states)
                projected_dynamic_states = self._metaworld_projection(dynamic_states)

                state_list.append(projected_dynamic_states)

            states = torch.stack(state_list, dim=2)  # (b, s, p, 2)

        dynamic_cond = self._dynamic_conditioning(image_feature_maps, states, state_cond)
        dynamic_cond = einops.rearrange(
            dynamic_cond, "(b s) ... -> b (s ...)", b=batch_size, s=n_obs_steps
        )  # (b, global_cond_dim)

        # Run the denoising network (that might denoise the trajectory, or attempt to predict the noise).
        pred = self.unet(noisy_trajectory, timesteps, global_cond=dynamic_cond)

        # Compute the loss.
        # The target is either the original trajectory, or the noise.
        if self.config.prediction_type == "epsilon":
            target = eps
        elif self.config.prediction_type == "sample":
            target = batch[ACTION]
        else:
            raise ValueError(f"Unsupported prediction type {self.config.prediction_type}")

        loss = F.mse_loss(pred, target, reduction="none")

        # Mask loss wherever the action is padded with copies (edges of the dataset trajectory).
        if self.config.do_mask_loss_for_padding:
            if "action_is_pad" not in batch:
                raise ValueError(
                    "You need to provide 'action_is_pad' in the batch when "
                    f"{self.config.do_mask_loss_for_padding=}."
                )
            in_episode_bound = ~batch["action_is_pad"]
            loss = loss * in_episode_bound.unsqueeze(-1)

        return loss.mean()


class DiffusionSinusoidalPosEmb(nn.Module):
    """1D sinusoidal positional embeddings as in Attention is All You Need."""

    def __init__(self, dim: int):
        super().__init__()
        self.dim = dim

    def forward(self, x: Tensor) -> Tensor:
        device = x.device
        half_dim = self.dim // 2
        emb = math.log(10000) / (half_dim - 1)
        emb = torch.exp(torch.arange(half_dim, device=device) * -emb)
        emb = x.unsqueeze(-1) * emb.unsqueeze(0)
        emb = torch.cat((emb.sin(), emb.cos()), dim=-1)
        return emb


class DiffusionConv1dBlock(nn.Module):
    """Conv1d --> GroupNorm --> Mish"""

    def __init__(self, inp_channels, out_channels, kernel_size, n_groups=8):
        super().__init__()

        self.block = nn.Sequential(
            nn.Conv1d(inp_channels, out_channels, kernel_size, padding=kernel_size // 2),
            nn.GroupNorm(n_groups, out_channels),
            nn.Mish(),
        )

    def forward(self, x):
        return self.block(x)


class DiffusionConditionalUnet1d(nn.Module):
    """A 1D convolutional UNet with FiLM modulation for conditioning.

    Note: this removes local conditioning as compared to the original diffusion policy code.
    """

    def __init__(self, config: OursDiffusionConfig, global_cond_dim: int):
        super().__init__()

        self.config = config

        # Encoder for the diffusion timestep.
        self.diffusion_step_encoder = nn.Sequential(
            DiffusionSinusoidalPosEmb(config.diffusion_step_embed_dim),
            nn.Linear(config.diffusion_step_embed_dim, config.diffusion_step_embed_dim * 4),
            nn.Mish(),
            nn.Linear(config.diffusion_step_embed_dim * 4, config.diffusion_step_embed_dim),
        )

        # The FiLM conditioning dimension.
        cond_dim = config.diffusion_step_embed_dim + global_cond_dim

        # In channels / out channels for each downsampling block in the Unet's encoder. For the decoder, we
        # just reverse these.
        in_out = [(config.action_feature.shape[0], config.down_dims[0])] + list(
            zip(config.down_dims[:-1], config.down_dims[1:], strict=True)
        )

        # Unet encoder.
        common_res_block_kwargs = {
            "cond_dim": cond_dim,
            "kernel_size": config.kernel_size,
            "n_groups": config.n_groups,
            "use_film_scale_modulation": config.use_film_scale_modulation,
        }
        self.down_modules = nn.ModuleList([])
        for ind, (dim_in, dim_out) in enumerate(in_out):
            is_last = ind >= (len(in_out) - 1)
            self.down_modules.append(
                nn.ModuleList(
                    [
                        DiffusionConditionalResidualBlock1d(dim_in, dim_out, **common_res_block_kwargs),
                        DiffusionConditionalResidualBlock1d(dim_out, dim_out, **common_res_block_kwargs),
                        # Downsample as long as it is not the last block.
                        nn.Conv1d(dim_out, dim_out, 3, 2, 1) if not is_last else nn.Identity(),
                    ]
                )
            )

        # Processing in the middle of the auto-encoder.
        self.mid_modules = nn.ModuleList(
            [
                DiffusionConditionalResidualBlock1d(
                    config.down_dims[-1], config.down_dims[-1], **common_res_block_kwargs
                ),
                DiffusionConditionalResidualBlock1d(
                    config.down_dims[-1], config.down_dims[-1], **common_res_block_kwargs
                ),
            ]
        )

        # Unet decoder.
        self.up_modules = nn.ModuleList([])
        for ind, (dim_out, dim_in) in enumerate(reversed(in_out[1:])):
            is_last = ind >= (len(in_out) - 1)
            self.up_modules.append(
                nn.ModuleList(
                    [
                        # dim_in * 2, because it takes the encoder's skip connection as well
                        DiffusionConditionalResidualBlock1d(dim_in * 2, dim_out, **common_res_block_kwargs),
                        DiffusionConditionalResidualBlock1d(dim_out, dim_out, **common_res_block_kwargs),
                        # Upsample as long as it is not the last block.
                        nn.ConvTranspose1d(dim_out, dim_out, 4, 2, 1) if not is_last else nn.Identity(),
                    ]
                )
            )

        self.final_conv = nn.Sequential(
            DiffusionConv1dBlock(config.down_dims[0], config.down_dims[0], kernel_size=config.kernel_size),
            nn.Conv1d(config.down_dims[0], config.action_feature.shape[0], 1),
        )

    def forward(self, x: Tensor, timestep: Tensor | int, global_cond=None) -> Tensor:
        """
        Args:
            x: (B, T, input_dim) tensor for input to the Unet.
            timestep: (B,) tensor of (timestep_we_are_denoising_from - 1).
            global_cond: (B, global_cond_dim)
            output: (B, T, input_dim)
        Returns:
            (B, T, input_dim) diffusion model prediction.
        """
        # For 1D convolutions we'll need feature dimension first.
        x = einops.rearrange(x, "b t d -> b d t")

        timesteps_embed = self.diffusion_step_encoder(timestep)

        # If there is a global conditioning feature, concatenate it to the timestep embedding.
        if global_cond is not None:
            global_feature = torch.cat([timesteps_embed, global_cond], axis=-1)
        else:
            global_feature = timesteps_embed

        # Run encoder, keeping track of skip features to pass to the decoder.
        encoder_skip_features: list[Tensor] = []
        for resnet, resnet2, downsample in self.down_modules:
            x = resnet(x, global_feature)
            x = resnet2(x, global_feature)
            encoder_skip_features.append(x)
            x = downsample(x)

        for mid_module in self.mid_modules:
            x = mid_module(x, global_feature)

        # Run decoder, using the skip features from the encoder.
        for resnet, resnet2, upsample in self.up_modules:
            x = torch.cat((x, encoder_skip_features.pop()), dim=1)
            x = resnet(x, global_feature)
            x = resnet2(x, global_feature)
            x = upsample(x)

        x = self.final_conv(x)

        x = einops.rearrange(x, "b d t -> b t d")
        return x


class DiffusionConditionalResidualBlock1d(nn.Module):
    """ResNet style 1D convolutional block with FiLM modulation for conditioning."""

    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        cond_dim: int,
        kernel_size: int = 3,
        n_groups: int = 8,
        # Set to True to do scale modulation with FiLM as well as bias modulation (defaults to False meaning
        # FiLM just modulates bias).
        use_film_scale_modulation: bool = False,
    ):
        super().__init__()

        self.use_film_scale_modulation = use_film_scale_modulation
        self.out_channels = out_channels

        self.conv1 = DiffusionConv1dBlock(in_channels, out_channels, kernel_size, n_groups=n_groups)

        # FiLM modulation (https://huggingface.co/papers/1709.07871) outputs per-channel bias and (maybe) scale.
        cond_channels = out_channels * 2 if use_film_scale_modulation else out_channels
        self.cond_encoder = nn.Sequential(nn.Mish(), nn.Linear(cond_dim, cond_channels))

        self.conv2 = DiffusionConv1dBlock(out_channels, out_channels, kernel_size, n_groups=n_groups)

        # A final convolution for dimension matching the residual (if needed).
        self.residual_conv = (
            nn.Conv1d(in_channels, out_channels, 1) if in_channels != out_channels else nn.Identity()
        )

    def forward(self, x: Tensor, cond: Tensor) -> Tensor:
        """
        Args:
            x: (B, in_channels, T)
            cond: (B, cond_dim)
        Returns:
            (B, out_channels, T)
        """
        out = self.conv1(x)

        # Get condition embedding. Unsqueeze for broadcasting to `out`, resulting in (B, out_channels, 1).
        cond_embed = self.cond_encoder(cond).unsqueeze(-1)
        if self.use_film_scale_modulation:
            # Treat the embedding as a list of scales and biases.
            scale = cond_embed[:, : self.out_channels]
            bias = cond_embed[:, self.out_channels :]
            out = scale * out + bias
        else:
            # Treat the embedding as biases.
            out = out + cond_embed

        out = self.conv2(out)
        out = out + self.residual_conv(x)
        return out
